// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YilmazLeague.DataAccessLayer.Context;

#nullable disable

namespace YilmazLeague.DataAccessLayer.Migrations
{
    [DbContext(typeof(YilmazLeagueDB))]
    partial class YilmazLeagueDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.LeagueMatch", b =>
                {
                    b.Property<int>("LeagueMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueMatchId"), 1L, 1);

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeagueMatchId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.MatchEvent", b =>
                {
                    b.Property<int>("MatchEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchEventId"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueMatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerInId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerOutId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("MatchEventId");

                    b.HasIndex("LeagueMatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerInId");

                    b.HasIndex("PlayerOutId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"), 1L, 1);

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            EndYear = 2024,
                            IsActive = false,
                            Name = "2023-2024",
                            StartYear = 2023
                        },
                        new
                        {
                            SeasonId = 2,
                            EndYear = 2025,
                            IsActive = false,
                            Name = "2024-2025",
                            StartYear = 2024
                        },
                        new
                        {
                            SeasonId = 3,
                            EndYear = 2026,
                            IsActive = true,
                            Name = "2025-2026",
                            StartYear = 2025
                        },
                        new
                        {
                            SeasonId = 4,
                            EndYear = 2027,
                            IsActive = false,
                            Name = "2026-2027",
                            StartYear = 2026
                        });
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"), 1L, 1);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.LeagueMatch", b =>
                {
                    b.HasOne("YilmazLeague.EntityLayer.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.MatchEvent", b =>
                {
                    b.HasOne("YilmazLeague.EntityLayer.Entities.LeagueMatch", "LeagueMatch")
                        .WithMany("MatchEvents")
                        .HasForeignKey("LeagueMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Player", "Player")
                        .WithMany("MatchEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Player", "PlayerIn")
                        .WithMany("PlayerInEvents")
                        .HasForeignKey("PlayerInId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Player", "PlayerOut")
                        .WithMany("PlayerOutEvents")
                        .HasForeignKey("PlayerOutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YilmazLeague.EntityLayer.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeagueMatch");

                    b.Navigation("Player");

                    b.Navigation("PlayerIn");

                    b.Navigation("PlayerOut");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Player", b =>
                {
                    b.HasOne("YilmazLeague.EntityLayer.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.LeagueMatch", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Player", b =>
                {
                    b.Navigation("MatchEvents");

                    b.Navigation("PlayerInEvents");

                    b.Navigation("PlayerOutEvents");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Season", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("YilmazLeague.EntityLayer.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
